name: Test

on:
  push:
    branches: [main, master]
    tags: ["*"]
  pull_request:

jobs:
  Test:
    name: Julia (v${{ matrix.version }}) on ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ### NOTE: Scope
        ###   - for testing and early development, focusing on just latest 
        ###     version testing against linux

        version:
          - 1 # automatically expands to the latest stable 1.x release of Julia
          # - 1.0
          # - nightly
        os:
          - ubuntu-latest
        arch:
          - x64
          # - x86
        # include:
        #   # test macOS and Windows with latest Julia only
        #   - os: macOS-latest
        #     arch: x64
        #     version: 1
        #   - os: windows-latest
        #     arch: x64
        #     version: 1
        #   - os: windows-latest
        #     arch: x86
        #     version: 1

    steps:
      - uses: actions/checkout@v2

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - uses: julia-actions/cache@v1

      - uses: julia-actions/julia-buildpkg@v1

      - uses: julia-actions/julia-runtest@v1

      - uses: julia-actions/julia-processcoverage@v1

      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
